apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: js-build
spec:
  stepTemplate:
    name: ""
    volumeMounts:
    - mountPath: /home/jenkins
      name: workspace-volume
    - mountPath: /etc/podinfo
      name: podinfo
      readOnly: true
    workingDir: /workspace/source
    env:
      - name: HOME
        value: /tekton/home
  steps:
    - name: build-npm-install
      image: node:18-slim
      script: |
        #!/bin/sh
        npm install
        echo "starting ngcc..."
        ./node_modules/.bin/ngcc
    - name: build-npm-test
      image: node:18-slim
      script: |
        #!/bin/sh
        CI=true DISPLAY=:99 npm test
    - name: build-npm-build
      resources:
        requests:
          cpu: 2
          memory: 4.5Gi
        limits:
          memory: 8Gi
      image: node:18-slim
      script: |
        #!/bin/sh
        CI=true DISPLAY=:99 npm run build
    - name: build-sentry-sourcemaps
      image: getsentry/sentry-cli
      env:
        - name: SENTRY_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: sentry
              key: auth-token
        - name: SENTRY_ORG
          valueFrom:
            secretKeyRef:
              name: sentry
              key: organisation-slug
      script: |
        INFORMATIONAL_VERSION=$(cat ../INFORMATIONAL_VERSION)
        SEMVER=$(cat ../SEMVER)
        echo $INFORMATIONAL_VERSION
        RELEASE_NAME=$REPO_NAME@$SEMVER
        export SENTRY_PROJECT=$REPO_NAME
        echo "Sending sourcemaps for release $RELEASE_NAME ..."
        sentry-cli releases files $RELEASE_NAME upload-sourcemaps dist
  volumes:
  - emptyDir: {}
    name: workspace-volume
  - downwardAPI:
      items:
      - fieldRef:
          fieldPath: metadata.labels
        path: labels
    name: podinfo
