apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pr-endpoint-deploy
spec:
  stepTemplate:
    name: ""
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
    volumeMounts:
      - mountPath: /home/jenkins
        name: workspace-volume
      - mountPath: /etc/podinfo
        name: podinfo
        readOnly: true
    workingDir: /workspace/source
    env:
      - name: HOME
        value: /tekton/home
  steps:
    - name: nuget-config-subst
      image: chrissena/dotnet-5.0-builder:1.0
      env:
        - name: NEXUS_USERNAME
          valueFrom:
            secretKeyRef:
              name: nexus-credentials
              key: username
        - name: NEXUS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nexus-credentials
              key: password
      script: |
        if [ $(cat /workspace/.skip) = "skip" ]
        then
          echo "skipping step"
          exit 0
        fi
        source .jx/variables.sh
        envsubst < nuget.config.template > nuget.config
  volumes:
  - emptyDir: {}
    name: workspace-volume
  - downwardAPI:
      items:
      - fieldRef:
          fieldPath: metadata.labels
        path: labels
    name: podinfo
